import React from 'react';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cavan Portfolio 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-gradient-to-tr from-blue-600 via-indigo-500 to-purple-500">
          <div>
            <h1 className="font-bold text-white text-center text-4xl mb-5">Front-end Web Developer</h1>
            <p className="text-center text-white text-2xl">I build for fun and for work</p>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
