import React from 'react';
import Head from 'next/head';

import Hero from '@components/organisms/Hero';
import Profile from '@components/organisms/Profile';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cavan Portfolio 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Profile />
      </main>

      {/* <footer></footer> */}
    </div>
  );
}
